### PR TITLE
Add, expand on, and standardize docstrings

### PR DESCRIPTION
**Pull request by GreenGiraffe1**
Update docstrings for:

deploy_tools.py
mycity_controller.py
lambda_function.py
utilities module
intents module

### CODE REVIEW

**Comment by GreenGiraffe1** [comment]
Implemented the requested changes by updating the variable descriptions that needed help and changing the way return values are documented.

**Comment by Joshhw** [comment]
Hey Matt, there seems to be some conflicts that occurred due to some recent merges, this will be good once they are dealt with. Let us know when you do that.

**Comment by GreenGiraffe1** [comment]
Don't review / merge this yet.  There's an issue I need to resolve.

**Comment by GreenGiraffe1** [comment]
Issue resolved.

**Comment by GreenGiraffe1** [comment]
I rebased my branch onto the new master branch and squashed my commits to make the project history cleaner.  I just realized this might make it a pain for whoever is reviewing the merge conflicts (because it will probably show all changes from all previous commits need to be reviewed).  Is there a way around this?  Would you like me to do this in a different way?

**Pull request merged**
