### PR TITLE
automagically update and upload lambda.

### PR DESCRIPTION
**Pull request by Joshhw**
This functionality allows for an additional parameter to the deploy_tool.py functionality. To run the new deploy tools you will want to call 
`python deploy_tools.py -p -f FUNCTION_NAME`

### CODE REVIEW

**Comment by jmartini** [comment]
I am getting the following error:
`Traceback (most recent call last):
  File "deploy_tools.py", line 226, in <module>
    main()
  File "deploy_tools.py", line 218, in main
    update_lambda_code()
  File "deploy_tools.py", line 136, in update_lambda_code
    run(update_lambda_code)
  File "C:\Users\Jamie Martini\AppData\Local\Programs\Python\Python36\Lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Jamie Martini\AppData\Local\Programs\Python\Python36\Lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Jamie Martini\AppData\Local\Programs\Python\Python36\Lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`


Does this require any command line tools to be installed??

**Comment by jmartini** [comment]
Lets add the instructions for installing the AWS CLI to the readme (https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html)

**Comment by jmartini** [comment]
Tested and working on Windows. Nice job!

**Comment by thiteixeira** [comment]
I suggest adding the following steps/requirements:

1. install `aws cli` using `pip install awscli --upgrade --user` (Linux)
2. Make sure an [IAM](https://console.aws.amazon.com/iam/home) user is created and has access to AWS services.
3. Configure `aws-cli` using `aws configure`. See [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html) for help. We use region `us-east-1`
4. Finally, run `python deploy_tools.py -p -f BostonData`.
If everything runs well, you should see the following message:

```
Updating/uploading lambda code

<a bunch of text>

TRACINGCONFIG	PassThrough
VPCCONFIG	
DONE UPLOADING...
```

**Pull request merged**
