### PR TITLE
Logging consolidation

### PR DESCRIPTION
**Pull request by NorwayMaple**
The changes I made are that I created a base logger at the top of the logger hierarchy in the file mycity/logger.py.  The loggers in the individual files inherit from this base logger through 

import mycity.logger

and the logger is instantiated in each file in the line

logger = logging.getLogger(__name__)

This eliminates the need to repeat many lines in each file to create the logger, handler, format, etc., as these are taken care of in mycity/logger.py.

As it is, debug messages are suppressed.  To make them visible, simply change

logger.setLevel(logging.INFO) # Must be changed for debug/verbose
to
logger.setLevel(logging.DEBUG)

Also, in the 'abe' branch (included in abe_new_logging branch), I made a correction of a CSV filename.

### CODE REVIEW

**Comment by NorwayMaple** [comment]
That's fine.  If we do make a decision I'd be glad to write a script to traverse the file structure and remove all \r from newlines.  (I actually tried something similar (locally) but it ended up removing all indent.)

**Comment by Joshhw** [comment]
Hey Abe, I tested your branch and didn't see any results in the cloud watch. Could you tell me how this is supposed to work?

**Comment by NorwayMaple** [comment]
Thanks for looking at my branch!  The reason you are not seeing results is that line 5 in mycity/logger.py is set to INFO.  Set it to DEBUG to get all the debug statements.  logger.py configures the logger for all of the other scripts that use it.

**Comment by curranjm** [comment]
Closing this per updates to @thiteixeira's PR. We should only need to execute logger configuration once.

**Pull request closed without merging**
