### PR TITLE
adding logging

### PR DESCRIPTION
**Pull request by thiteixeira**
Added logging to Intents, utility finders, and controller.

`run_tests.py` work with the following output:
```
Ran 32 tests in 0.491s

OK
```

### CODE REVIEW

**Comment by jmartini** [comment]
Crash has been fixed, thanks! Looks like there are still a few raw print statements in here (ex: `lambda_handler.py:121`. Lets convert these all to the new logging system. 

I have filed another logging improvement #120 that doesn't need to be included here but I think would be a good improvement.

**Comment by jmartini** [comment]
Ah yes sorry, I mistyped. `lambda_function.py:121` is the one I saw. Just to be clear, a search reveals a bunch of print statements still in the code. Not sure if every one is valid, but if they are, lets convert to log statements.
```
./intents/get_alerts_intent.py:66:`    print("[dictionary with alerts scraped from boston.gov]:\n" + str(alerts))
./intents/get_alerts_intent.py:68:    print("[dictionary after pruning]:\n" + str(alerts))
./intents/snow_parking_intent.py:55:        print("Finding snow emergency parking for {}".format(finder.origin_address))
./intents/snow_parking_intent.py:60:        print("Error: Called snow_parking_intent with no address")
./intents/trash_intent.py:60:        print("Error: Called trash_day_intent with no address")
./intents/trash_intent.py:117:        print("Error getting ReCollect API info. Got response: {}"
./intents/trash_intent.py:143:        print("Error getting trash info from ReCollect API info. "
./intents/user_address_intent.py:51:    # print("GETTING ADDRESS FROM SESSION")
/mycity_response_data_model.py:115:            print("Error: {} is not a valid directive".format(value))
/utilities/address_utils.py:18:    print(
./utilities/gis_utils.py:31:    print(
./utilities/gis_utils.py:54:        print(error_message)
./utilities/gis_utils.py:73:    print(
./utilities/gis_utils.py:98:    print(
./utilities/google_maps_utils.py:32:    print(
./utilities/google_maps_utils.py:55:            print("Failed to get driving directions")
./utilities/google_maps_utils.py:67:    print(
./utilities/google_maps_utils.py:94:    print(
./utilities/google_maps_utils.py:124:                print("Could not parse driving info {}".format(driving_data))
./utilities/google_maps_utils.py:145:    print(

```

**Comment by thiteixeira** [comment]
Added logging statements in all files. Unit tests return:

```
Ran 32 tests in 0.891s

OK

```

**Comment by Joshhw** [comment]
@thiteixeira this branch has some merge conflicts, could you fix them? afterwards I will pull it down and test it.

**Comment by thiteixeira** [comment]
I guess this issue has been resolved by [pull request 131](https://github.com/codeforboston/voiceapp311/pull/131/)

I fixed the conflicts there too.

**Comment by Joshhw** [comment]
Make sure to change all the print statements to logging.

**Comment by curranjm** [comment]
I pulled @thiteixeira's branch down and made some updates and pushed it back up.
- Removed code changes related to other tickets (I think this was mainly food truck code)
- Rebased onto current master
- Removed mycity.logger and any references to it
    - This file is unnecessary. Instead we can do all the configuration we need in a couple of lines on entry to the app in lambda_function and this carries over to loggers we instantiate in any module where we want logging. Because of this, we need to remove the default handlers Amazon adds or our log statements don't show up in cloudwatch (see https://stackoverflow.com/a/14602233/2554154).
- Did some misc cleanup in the course of updating logging statements to get rid of PEP8 code sniffs.
    - Removed the `future` imports as they only affected `print` statements, which have all been removed

**Comment by thiteixeira** [comment]
Hi @Joshhw,
I'll pull the code and fix the log statements. 
Initially, I just turned the print statements into logs. Do you have any preferences for the format?

@curranjm you mentioned on Slack that you worked on the log. Do you have any comments?

Thanks

**Comment by curranjm** [comment]
@thiteixeira -- I talked to Josh about this and I can make the change. Thanks.

**Comment by curranjm** [comment]
@jmartini 
@Joshhw 

The logging works now and the `\r` solution I mentioned before works for grouping multiline log statements into one cloudwatch line, so I added that fix into this as well.

This one should be good to merge.

**Comment by Joshhw** [comment]
the structure of the debug logs looks great!

**Comment by jmartini** [comment]
Changes to `deploy_tools.py` do not work

**Comment by jmartini** [comment]
Improved logging looks great!!

**Pull request merged**
